<a href="https://colab.research.google.com/github/Azimoj/TensorFlow/blob/main/Tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.13.0


https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2


https://github.com/aladdinpersson/Machine-Learning-Collection/blob/master/ML/TensorFlow/Basics/tutorial3-neuralnetwork.py

In [3]:
# initialization of tensors
x= tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [6]:
x2= tf.constant(4,shape=(1,1), dtype=tf.float32)
x2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x = tf.eye(3)
print(x)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.ones((4, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [10]:
x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [11]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.32635462 0.28474295]
 [0.3974589  0.27457666]], shape=(2, 2), dtype=float32)


In [12]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

tf.Tensor(
[[ 0.79813921  0.87488639  1.30329335]
 [ 0.2552776  -0.24284638 -0.76134551]
 [-0.34691864 -1.56415665  0.82802039]], shape=(3, 3), dtype=float64)


In [13]:
x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [ ]:
# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5



In [15]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)

In [16]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.8499169 , -1.2494192 ,  1.4972056 ],
       [ 0.00362328, -0.4224678 , -0.0707971 ]], dtype=float32)>

In [17]:
y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0047814 ,  0.18873787],
       [ 0.9050158 ,  2.8888524 ],
       [ 0.07886289,  0.73140156]], dtype=float32)>

In [18]:
z

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.84609175, -2.8634787 ],
       [-0.3915639 , -1.2715442 ]], dtype=float32)>

In [20]:
z = x @ y
z

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.84609175, -2.8634787 ],
       [-0.3915639 , -1.2715442 ]], dtype=float32)>

In [23]:
x = tf.random.normal((2, 2))
x


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.01592004, -1.1250492 ],
       [-0.6993682 , -0.67407   ]], dtype=float32)>

In [24]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])

In [25]:
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [26]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [27]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [28]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [29]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [31]:
indices = tf.constant([0, 3])
indices

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>

In [33]:
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [32]:
x_indices = tf.gather(x, indices)
x_indices

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

In [35]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])


In [36]:
print(x[0, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [37]:
print(x[0:2, :])


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [40]:
# Reshaping
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [41]:
x = tf.reshape(x, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [42]:
x = tf.transpose(x, perm=[1, 0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>